/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { BaseResponse_boolean_ } from './models/BaseResponse_boolean_';
export type { BaseResponse_CompeteExamVO_ } from './models/BaseResponse_CompeteExamVO_';
export type { BaseResponse_CompeteVo_ } from './models/BaseResponse_CompeteVo_';
export type { BaseResponse_CompetitionVO_ } from './models/BaseResponse_CompetitionVO_';
export type { BaseResponse_ExamPaperVO_ } from './models/BaseResponse_ExamPaperVO_';
export type { BaseResponse_int_ } from './models/BaseResponse_int_';
export type { BaseResponse_List_long_ } from './models/BaseResponse_List_long_';
export type { BaseResponse_List_MessageVo_ } from './models/BaseResponse_List_MessageVo_';
export type { BaseResponse_List_Tag_ } from './models/BaseResponse_List_Tag_';
export type { BaseResponse_LoginUserVO_ } from './models/BaseResponse_LoginUserVO_';
export type { BaseResponse_long_ } from './models/BaseResponse_long_';
export type { BaseResponse_Page_Comment_ } from './models/BaseResponse_Page_Comment_';
export type { BaseResponse_Page_CommentVo_ } from './models/BaseResponse_Page_CommentVo_';
export type { BaseResponse_Page_CompeteExam_ } from './models/BaseResponse_Page_CompeteExam_';
export type { BaseResponse_Page_CompeteExamVO_ } from './models/BaseResponse_Page_CompeteExamVO_';
export type { BaseResponse_Page_CompeteVo_ } from './models/BaseResponse_Page_CompeteVo_';
export type { BaseResponse_Page_Competition_ } from './models/BaseResponse_Page_Competition_';
export type { BaseResponse_Page_CompetitionVO_ } from './models/BaseResponse_Page_CompetitionVO_';
export type { BaseResponse_Page_ExamPaper_ } from './models/BaseResponse_Page_ExamPaper_';
export type { BaseResponse_Page_FriendApplyVo_ } from './models/BaseResponse_Page_FriendApplyVo_';
export type { BaseResponse_Page_Post_ } from './models/BaseResponse_Page_Post_';
export type { BaseResponse_Page_PostVO_ } from './models/BaseResponse_Page_PostVO_';
export type { BaseResponse_Page_ProductInfo_ } from './models/BaseResponse_Page_ProductInfo_';
export type { BaseResponse_Page_ProductOrder_ } from './models/BaseResponse_Page_ProductOrder_';
export type { BaseResponse_Page_QuestionBank_ } from './models/BaseResponse_Page_QuestionBank_';
export type { BaseResponse_Page_QuestionBankVo_ } from './models/BaseResponse_Page_QuestionBankVo_';
export type { BaseResponse_Page_QuestionVO_ } from './models/BaseResponse_Page_QuestionVO_';
export type { BaseResponse_Page_Tag_ } from './models/BaseResponse_Page_Tag_';
export type { BaseResponse_Page_Team_ } from './models/BaseResponse_Page_Team_';
export type { BaseResponse_Page_TeamVO_ } from './models/BaseResponse_Page_TeamVO_';
export type { BaseResponse_Page_User_ } from './models/BaseResponse_Page_User_';
export type { BaseResponse_Page_UserFriendDTO_ } from './models/BaseResponse_Page_UserFriendDTO_';
export type { BaseResponse_Page_UserVO_ } from './models/BaseResponse_Page_UserVO_';
export type { BaseResponse_PostVO_ } from './models/BaseResponse_PostVO_';
export type { BaseResponse_ProductInfo_ } from './models/BaseResponse_ProductInfo_';
export type { BaseResponse_QuestionBankVo_ } from './models/BaseResponse_QuestionBankVo_';
export type { BaseResponse_QuestionVO_ } from './models/BaseResponse_QuestionVO_';
export type { BaseResponse_string_ } from './models/BaseResponse_string_';
export type { BaseResponse_TeamVO_ } from './models/BaseResponse_TeamVO_';
export type { BaseResponse_User_ } from './models/BaseResponse_User_';
export type { BaseResponse_UserFriendDTO_ } from './models/BaseResponse_UserFriendDTO_';
export type { BaseResponse_UserPaper_ } from './models/BaseResponse_UserPaper_';
export type { BaseResponse_UserPaperQuestionVo_ } from './models/BaseResponse_UserPaperQuestionVo_';
export type { BaseResponse_UserPaperVo_ } from './models/BaseResponse_UserPaperVo_';
export type { BaseResponse_UserVO_ } from './models/BaseResponse_UserVO_';
export type { ChatRequest } from './models/ChatRequest';
export type { Comment } from './models/Comment';
export type { CommentAddRequest } from './models/CommentAddRequest';
export type { CommentLikeAddRequest } from './models/CommentLikeAddRequest';
export type { CommentQueryRequest } from './models/CommentQueryRequest';
export type { CommentVo } from './models/CommentVo';
export type { CompeteExam } from './models/CompeteExam';
export type { CompeteExamAddRequest } from './models/CompeteExamAddRequest';
export type { CompeteExamQueryRequest } from './models/CompeteExamQueryRequest';
export type { CompeteExamUpdateRequest } from './models/CompeteExamUpdateRequest';
export type { CompeteExamVO } from './models/CompeteExamVO';
export type { CompeteQueryRequest } from './models/CompeteQueryRequest';
export type { CompeteUserVo } from './models/CompeteUserVo';
export type { CompeteVo } from './models/CompeteVo';
export type { Competition } from './models/Competition';
export type { CompetitionAddRequest } from './models/CompetitionAddRequest';
export type { CompetitionEditRequest } from './models/CompetitionEditRequest';
export type { CompetitionQueryRequest } from './models/CompetitionQueryRequest';
export type { CompetitionUpdateRequest } from './models/CompetitionUpdateRequest';
export type { CompetitionVO } from './models/CompetitionVO';
export type { DeleteRequest } from './models/DeleteRequest';
export type { ExamPaper } from './models/ExamPaper';
export type { ExamPaperAddRequest } from './models/ExamPaperAddRequest';
export type { ExamPaperQueryRequest } from './models/ExamPaperQueryRequest';
export type { ExamPaperUpdateRequest } from './models/ExamPaperUpdateRequest';
export type { ExamPaperVO } from './models/ExamPaperVO';
export type { FriendApplyRequest } from './models/FriendApplyRequest';
export type { FriendApplyVo } from './models/FriendApplyVo';
export type { FriendsQueryRequest } from './models/FriendsQueryRequest';
export type { IdRequest } from './models/IdRequest';
export type { JoinCompeteRequest } from './models/JoinCompeteRequest';
export type { LoginUserVO } from './models/LoginUserVO';
export type { MessageVo } from './models/MessageVo';
export type { OrderItem } from './models/OrderItem';
export type { Page_Comment_ } from './models/Page_Comment_';
export type { Page_CommentVo_ } from './models/Page_CommentVo_';
export type { Page_CompeteExam_ } from './models/Page_CompeteExam_';
export type { Page_CompeteExamVO_ } from './models/Page_CompeteExamVO_';
export type { Page_CompeteVo_ } from './models/Page_CompeteVo_';
export type { Page_Competition_ } from './models/Page_Competition_';
export type { Page_CompetitionVO_ } from './models/Page_CompetitionVO_';
export type { Page_ExamPaper_ } from './models/Page_ExamPaper_';
export type { Page_FriendApplyVo_ } from './models/Page_FriendApplyVo_';
export type { Page_Post_ } from './models/Page_Post_';
export type { Page_PostVO_ } from './models/Page_PostVO_';
export type { Page_ProductInfo_ } from './models/Page_ProductInfo_';
export type { Page_ProductOrder_ } from './models/Page_ProductOrder_';
export type { Page_QuestionBank_ } from './models/Page_QuestionBank_';
export type { Page_QuestionBankVo_ } from './models/Page_QuestionBankVo_';
export type { Page_QuestionVO_ } from './models/Page_QuestionVO_';
export type { Page_Tag_ } from './models/Page_Tag_';
export type { Page_Team_ } from './models/Page_Team_';
export type { Page_TeamVO_ } from './models/Page_TeamVO_';
export type { Page_User_ } from './models/Page_User_';
export type { Page_UserFriendDTO_ } from './models/Page_UserFriendDTO_';
export type { Page_UserVO_ } from './models/Page_UserVO_';
export type { PageRequest } from './models/PageRequest';
export type { PaperQuestionAddRequest } from './models/PaperQuestionAddRequest';
export type { Post } from './models/Post';
export type { PostAddRequest } from './models/PostAddRequest';
export type { PostEditRequest } from './models/PostEditRequest';
export type { PostFavourAddRequest } from './models/PostFavourAddRequest';
export type { PostFavourQueryRequest } from './models/PostFavourQueryRequest';
export type { PostQueryRequest } from './models/PostQueryRequest';
export type { PostThumbAddRequest } from './models/PostThumbAddRequest';
export type { PostUpdateRequest } from './models/PostUpdateRequest';
export type { PostVO } from './models/PostVO';
export type { ProductInfo } from './models/ProductInfo';
export type { ProductInfoAddRequest } from './models/ProductInfoAddRequest';
export type { ProductInfoQueryRequest } from './models/ProductInfoQueryRequest';
export type { ProductInfoUpdateRequest } from './models/ProductInfoUpdateRequest';
export type { ProductOrder } from './models/ProductOrder';
export type { ProductOrderQueryRequest } from './models/ProductOrderQueryRequest';
export type { QuestionAddRequest } from './models/QuestionAddRequest';
export type { QuestionAnswerAddRequest } from './models/QuestionAnswerAddRequest';
export type { QuestionAnswerUpdateRequest } from './models/QuestionAnswerUpdateRequest';
export type { QuestionAnswerVO } from './models/QuestionAnswerVO';
export type { QuestionBank } from './models/QuestionBank';
export type { QuestionBankAddRequest } from './models/QuestionBankAddRequest';
export type { QuestionBankQueryRequest } from './models/QuestionBankQueryRequest';
export type { QuestionBankQuestionQueryRequest } from './models/QuestionBankQuestionQueryRequest';
export type { QuestionBankUpdateRequest } from './models/QuestionBankUpdateRequest';
export type { QuestionBankVo } from './models/QuestionBankVo';
export type { QuestionQueryRequest } from './models/QuestionQueryRequest';
export type { QuestionUpdateRequest } from './models/QuestionUpdateRequest';
export type { QuestionVO } from './models/QuestionVO';
export type { Reply } from './models/Reply';
export type { StartTheExamRequest } from './models/StartTheExamRequest';
export type { Tag } from './models/Tag';
export type { TagAddRequest } from './models/TagAddRequest';
export type { TagQueryRequest } from './models/TagQueryRequest';
export type { Team } from './models/Team';
export type { TeamAddRequest } from './models/TeamAddRequest';
export type { TeamEditRequest } from './models/TeamEditRequest';
export type { TeamJoinRequest } from './models/TeamJoinRequest';
export type { TeamKickOutRequest } from './models/TeamKickOutRequest';
export type { TeamQueryRequest } from './models/TeamQueryRequest';
export type { TeamTransferOfIdentityRequest } from './models/TeamTransferOfIdentityRequest';
export type { TeamUpdateRequest } from './models/TeamUpdateRequest';
export type { TeamVO } from './models/TeamVO';
export type { UpdateFriendRemark } from './models/UpdateFriendRemark';
export type { User } from './models/User';
export type { UserAddRequest } from './models/UserAddRequest';
export type { UserAnswer } from './models/UserAnswer';
export type { UserBindEmailRequest } from './models/UserBindEmailRequest';
export type { UserEmailLoginRequest } from './models/UserEmailLoginRequest';
export type { UserEmailRegisterRequest } from './models/UserEmailRegisterRequest';
export type { UserFriendDTO } from './models/UserFriendDTO';
export type { UserLoginRequest } from './models/UserLoginRequest';
export type { UserPaper } from './models/UserPaper';
export type { UserPaperAnswerRequest } from './models/UserPaperAnswerRequest';
export type { UserPaperQueryRequest } from './models/UserPaperQueryRequest';
export type { UserPaperQuestionVo } from './models/UserPaperQuestionVo';
export type { UserPaperVo } from './models/UserPaperVo';
export type { UserPasswordUpdateRequest } from './models/UserPasswordUpdateRequest';
export type { UserQueryRequest } from './models/UserQueryRequest';
export type { UserRegisterRequest } from './models/UserRegisterRequest';
export type { UserUnBindEmailRequest } from './models/UserUnBindEmailRequest';
export type { UserUpdateMyRequest } from './models/UserUpdateMyRequest';
export type { UserUpdateRequest } from './models/UserUpdateRequest';
export type { UserVO } from './models/UserVO';
export type { WebSocketVo } from './models/WebSocketVo';

export { ChatControllerService } from './services/ChatControllerService';
export { CommentControllerService } from './services/CommentControllerService';
export { CommentLikeControllerService } from './services/CommentLikeControllerService';
export { CompeteControllerService } from './services/CompeteControllerService';
export { CompeteExamControllerService } from './services/CompeteExamControllerService';
export { CompetitionControllerService } from './services/CompetitionControllerService';
export { ExamPaperControllerService } from './services/ExamPaperControllerService';
export { FileControllerService } from './services/FileControllerService';
export { FriendsApplyControllerService } from './services/FriendsApplyControllerService';
export { FriendsControllerService } from './services/FriendsControllerService';
export { JoinCompeteControllerService } from './services/JoinCompeteControllerService';
export { PostControllerService } from './services/PostControllerService';
export { PostFavourControllerService } from './services/PostFavourControllerService';
export { PostThumbControllerService } from './services/PostThumbControllerService';
export { ProductInfoControllerService } from './services/ProductInfoControllerService';
export { ProductOrderControllerService } from './services/ProductOrderControllerService';
export { QuestionBankControllerService } from './services/QuestionBankControllerService';
export { QuestionControllerService } from './services/QuestionControllerService';
export { TagControllerService } from './services/TagControllerService';
export { TeamControllerService } from './services/TeamControllerService';
export { UserControllerService } from './services/UserControllerService';
